services:
  - type: web
    name: aqumen-api
    runtime: python
    region: oregon
    plan: free
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_SESSION_TOKEN
        sync: false
      - key: AWS_DEFAULT_REGION
        value: us-west-2
      - key: PYTHON_VERSION
        value: 3.11.0
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn api_server:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
